# Generated by Django 4.2.11 on 2024-04-10 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_Answer',
            new_name='QuestionAnswer',
        ),
        migrations.RenameModel(
            old_name='Question_Answer_Message',
            new_name='QuestionAnswerMessage',
        ),
    ]
