run-server:
	poetry run python manage.py runserver

run-test:
	poetry run python manage.py test

run-coverage-test:
	poetry run coverage run manage.py test

run-coverage-report:
	poetry run coverage report